### ISSUE TITLE
Import value from constraints does not do anything

### ISSUE THREAD

**Issue by tre4b** [mwganson/DynamicData#64]
selecting the dd object and a sketch (both hidden and visible tried.

The import initialises a popup that gives me the chance to abort.   I choose go ahead and nothing happens.

I made sure I was running the most modern version.
I have tried adding an item manually to the dd first and also doing this from empty.
I have tried names that are both one word and multiple
I have removed and re added DD to make sure there was no issue with the install.

Nothing actually gets added to the list despite having more than 6 named properties in the sketch.

On the new version I get a listbox for the entry type when I add a value and changing the value indicated in the document in the parameters did not change anything.  I also have to open DD before it sticks in the menu even though the option is ticked.  I wondered if this helps indicate what may be going on.

**Comment by mwganson** [comment]
I am unable to reproduce the issue.  I created a new sketch, added a rectangle, constrained the horizontal edge with a constraint named "width" and the vertical edge with a constraint named "depth".  Then I went to dd workbench, created new dd object, selected the dd object and the sketch, and was able to import both named constraints.  You may create a new topic on the freecad forum help board and attach the file you are attempting to import for further assistance.

You must visit the workbench in order to get the toolbar.  But in 0.20 there is an option in edit -> preferences -> workbenches to autoload various workbenches upon startup.

**Comment by tre4b** [comment]
Hi mwganson

I've included my file here.   I have mucked about with it quite a bit to try and understand this.   I tried moving the location of the DD store around.  

When I started the drawing the first thing I created was the DD store.  I then added a Part,  added a body to the part and created the sketch and pad.   It was when I added the second sketch that I wanted to pull in the info from the Button Push sketch into the DD store.

I have tried the store in the part and removing the part and just having the body etc.   Nothing seemed to work.

[SuitcaseButton.zip](https://github.com/mwganson/DynamicData/files/9301979/SuitcaseButton.zip)

[code]
OS: Windows 10 (10.0)
Word size of FreeCAD: 64-bit
Version: 0.20.29045 (Git)
Build type: Release
Branch: master
Hash: af811b34b3
Python 3.8.13, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: English/United Kingdom (en_GB)
Installed mods: 
  * DynamicData 2.46.0
[/code]

**Comment by mwganson** [comment]
Don't use spaces in names of sketches or constraints.  Replaces spaces with underscores and try again.

**Comment by tre4b** [comment]
Hi mwganson,

That was it.   Damn, I should have thought to try that.   I did take the spaces out of one of the dimension names but I did not think about the Sketch names.     Took them out of the sketch names and all dimensions and they work just fine.   Also added DD to the autoload.   Thank you for your help, sorry for such a dumb query...
